### ISSUE TITLE
Error after recording end

### ISSUE THREAD

**Issue by ManishThapa123** [Tougee/AudioRecorderView#12]
E/AppSignatureHelper: Exception with recording stream
    java.io.IOException: Stream Closed
        at java.io.FileOutputStream.write(FileOutputStream.java:385)
        at com.twango.me.Utils.AudioRecorder$1.run(AudioRecorder.java:86)

**Comment by Tougee** [comment]
I guess this may be a problem with your recording，not associate with this View
